src/ps_ajax_guide/urls.py
from django.contrib import admin
from django.urls import path
from my_app.views import (
    indexView,
    postFriend, 
    checkNickName,
    FriendView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexView),
    path('post/ajax/friend', postFriend, name = "post_friend"),
    path('get/ajax/validate/nickname', checkNickName, name = "validate_nickname"),

    path("cbv/", FriendView.as_view(), name = "friend_cbv")

]

src/my_app/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
    # NICK NAME should be unique
    nick_name = models.CharField(max_length=100, unique =  True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    likes = models.CharField(max_length = 250)
    dob = models.DateField(auto_now=False, auto_now_add=False)
    lives_in = models.CharField(max_length=150, null = True, blank = True)

    def __str__(self):
        return self.first_name + self.last_name

src/my_app/forms.py
from .models import Friend
from django import forms
import datetime

class FriendForm(forms.ModelForm):
    ## change the widget of the date field.
    dob = forms.DateField(
        label='What is your birth date?', 
        # change the range of the years from 1980 to currentYear - 5
        widget=forms.SelectDateWidget(years=range(1980, datetime.date.today().year-5))
    )
    
    def __init__(self, *args, **kwargs):
        super(FriendForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Friend
        fields = ("__all__")

src/my_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.core import serializers
from .forms import FriendForm
from .models import Friend

from django.views import View

def indexView(request):
    form = FriendForm()
    friends = Friend.objects.all()
    return render(request, "index.html", {"form": form, "friends": friends})


def postFriend(request):
    # request should be ajax and method should be POST.
    if request.is_ajax and request.method == "POST":
        # get the form data
        form = FriendForm(request.POST)
        # save the data and after fetch the object in instance
        if form.is_valid():
            instance = form.save()
            # serialize in new friend object in json
            ser_instance = serializers.serialize('json', [ instance, ])
            # send to client side.
            return JsonResponse({"instance": ser_instance}, status=200)
        else:
            # some form errors occured.
            return JsonResponse({"error": form.errors}, status=400)

    # some error occured
    return JsonResponse({"error": ""}, status=400)

# BONUS CBV
def checkNickName(request):
    # request should be ajax and method should be GET.
    if request.is_ajax and request.method == "GET":
        # get the nick name from the client side.
        nick_name = request.GET.get("nick_name", None)
        # check for the nick name in the database.
        if Friend.objects.filter(nick_name = nick_name).exists():
            # if nick_name found return not valid new friend
            return JsonResponse({"valid":False}, status = 200)
        else:
            # if nick_name not found, then user can create a new friend.
            return JsonResponse({"valid":True}, status = 200)

    return JsonResponse({}, status = 400)
    



class FriendView(View):
    form_class = FriendForm
    template_name = "index.html"

    def get(self, *args, **kwargs):
        form = self.form_class()
        friends = Friend.objects.all()
        return render(self.request, self.template_name, 
            {"form": form, "friends": friends})

    def post(self, *args, **kwargs):
        # request should be ajax and method should be POST.
        if self.request.is_ajax and self.request.method == "POST":
            # get the form data
            form = self.form_class(self.request.POST)
            # save the data and after fetch the object in instance
            if form.is_valid():
                instance = form.save()
                # serialize in new friend object in json
                ser_instance = serializers.serialize('json', [ instance, ])
                # send to client side.
                return JsonResponse({"instance": ser_instance}, status=200)
            else:
                # some form errors occured.
                return JsonResponse({"error": form.errors}, status=400)

        # some error occured
        return JsonResponse({"error": ""}, status=400)

src/my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    {% block style %}
    {% endblock style %}
</head>

<body>
    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

src/my_app/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <form id="friend-form">
        <div class="row">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group col-4">
                <label class="col-12">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            
            <div class="col text-center">
                <input type="submit" class="btn btn-primary" value="Create Friend" />
            </div>
        </div>
    </form>
</div>

<hr />

<div class="container-fluid">
    <table class="table table-striped table-sm" id="my_friends">
        <thead>
            <tr>
                <th>Nick name</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Likes</th>
                <th>DOB</th>
                <th>Lives in</th>
            </tr>
        </thead>
        <tbody>
        {% for friend in friends %}
        <tr>
            <td>{{ friend.nick_name }}</td>
            <td>{{ friend.first_name }}</td>
            <td>{{ friend.last_name }}</td>
            <td>{{ friend.likes }}</td>
            <td>{{ friend.dob | date:"Y-m-d" }}</td>
            <td>{{ friend.lives_in }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

{% block javascript %}
<script>
    $(document).ready(function () {
        /*
            On submitting the form, send the POST AJAX
            request to server and after successful submission
            display the object.
        */
        $("#friend-form").submit(async function (e) {
            // Preventing from page reload and default actions
            e.preventDefault();
            // Serialize the data for sending the form data.
            var serializedData = $(this).serialize();
            console.log(serializedData);
            
            try {
                // Make POST AJAX call
                const response = await $.ajax({
                    type: 'POST',
                    url: "{% url 'post_friend' %}",
                    data: serializedData
                });
                
                // On successful creation of object
                // 1. Clear the form.
                $("#friend-form").trigger('reset');
                // 2. Focus to nickname input 
                $("#id_nick_name").focus();

                // Display the newly friend in the table.
                var instance = JSON.parse(response["instance"]);
                var fields = instance[0]["fields"];
                $("#my_friends tbody").prepend(
                    `<tr>
                    <td>${fields["nick_name"] || ""}</td>
                    <td>${fields["first_name"] || ""}</td>
                    <td>${fields["last_name"] || ""}</td>
                    <td>${fields["likes"] || ""}</td>
                    <td>${fields["dob"] || ""}</td>
                    <td>${fields["lives_in"] || ""}</td>
                    </tr>`
                );
            } catch (error) {
                // Alert the error if any error occurred
                alert(error.responseJSON ? error.responseJSON.error : 'An error occurred.');
            }
        });

        /*
        On focus out on input nickname,
        call AJAX get request to check if the nickName
        already exists or not.
        */
        $("#id_nick_name").focusout(async function (e) {
            e.preventDefault();
            // Get the nickname
            var nick_name = $(this).val();
            // GET AJAX request
            try {
                const response = await $.ajax({
                    type: 'GET',
                    url: "{% url 'validate_nickname' %}",
                    data: { "nick_name": nick_name }
                });
                
                // If not valid user, alert the user
                if (!response["valid"]) {
                    alert("You cannot create a friend with the same nickname");
                    var nickName = $("#id_nick_name");
                    nickName.val("");
                    nickName.focus();
                }
            } catch (error) {
                console.log(error);
            }
        });
    });
</script>
{% endblock javascript %}